### ISSUE TITLE
여행 기간 ui view 구현

### ISSUE THREAD

**Issue by hyeonheebee** [DeveloperAcademy-POSTECH/2024-MacC-A6-Five-Guys#23]
## Description
> 여행 기간 ui view 구현을 위한 브랜치를 새로 생성합니다 
git 충돌로 기존 브랜치 접근이 불가하여 브랜치를 새로 생성했습니다. 

</br>

## To-do

- [ ] 기존 코드 복원 하기 
- [ ] 기존코드 - extension 폰트, 컬러 적용하기 
- [ ] 여행기간 ui view 구현하기 

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.

**Comment by hyeonheebee** [comment]
스프린트 2로
