### ISSUE TITLE
image registration view 구현

### ISSUE THREAD

**Issue by hyeyeonie** [DeveloperAcademy-POSTECH/2024-MacC-A6-Five-Guys#26]
## Description
> 이미지를 등록하는 뷰의 레이아웃과 로직을 구현합니다.

</br>

## To-do

- [x] 버튼을 누르면 앨범 불러오기
- [x] 앨범에서 최소 3장 ~ 최대 5장의 사진 셀렉할 수 있게 구현하기
- [ ] 메타데이터와 연결해서 각 뷰에 해당하는 정보 보여주기

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
