### ISSUE TITLE
DailyProgressView 레이아웃 구현

### ISSUE THREAD

**Issue by hyeyeonie** [DeveloperAcademy-POSTECH/2024-MacC-A6-Five-Guys#41]
## Description
> 독서 일일 진행 상황을 기록하는 뷰의 레이아웃을 구현합니다.

</br>

## To-do

- [x] DailyProgressView 레이아웃 구현
- [x] 숫자 키보드 올라오도록 구현
- [x] 독서 마지막 종료일 문구UI 변경

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
