### ISSUE TITLE
OpenAI API 연동한 테스팅 뷰 그리기

### ISSUE THREAD

**Issue by zaehorang** [DeveloperAcademy-POSTECH/2024-MacC-A6-Five-Guys#6]
## Description
> OpenAI를 연동해서 AI와 채팅하는 테스팅 뷰를 작성합니다.

</br>

## To-do

- [ ] API key 등록하기
- [ ] API 통신 코드 작성하기
- [ ] 테스팅 채팅 뷰 작성하기

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.

**Comment by zaehorang** [comment]
주요 feature 변경으로 잠시 stop
