### ISSUE TITLE
도서 검색결과 없을때 화면 추가하기 

### ISSUE THREAD

**Issue by hyeonheebee** [DeveloperAcademy-POSTECH/2024-MacC-A6-Five-Guys#80]
## Description
> 도서 검색 결과 값이 빈 값이거나, 값이 없다는 것을 확인하고 값에따라 해당 상황을 분기처리해주기

</br>

## To-do

- [x] 도서 검색 결과 값이 빈 값이거나, 값이 없다는 것을 확인하는 지표 찾거나 만들기
- [x] 위의 지표에 따라 분기처리
- [x] 분기처리 후 화면표시 여부 

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.

**Comment by hyeonheebee** [comment]
적용되어 이슈 close 합니다
