### ISSUE TITLE
사진을 동영상 형태로 보여주기

### ISSUE THREAD

**Issue by zaehorang** [DeveloperAcademy-POSTECH/2024-MacC-A6-Five-Guys#9]
## Description
> 사진을 동영상 형태로 보여주는 테스팅 뷰를 추가합니다.

</br>

## To-do

- [ ] 개념 조사하기
- [ ] 구현 방법 확정하기
- [ ] 이미지 받는 코드 구현하기
- [ ] 영상처럼 보이게 하는 코드 구현하기
- [ ] 테스팅 뷰 그리기

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
