### ISSUE TITLE
책 범퍼 쪽수 입력 기능 추가

### ISSUE THREAD

**Issue by zaehorang** [DeveloperAcademy-POSTECH/2024-MacC-A6-Five-Guys#98]
## Description
> 책 추가 시, 시작 페이지와 끝 페이지를 설정할 수 있도록 수정합니다.
>- 책의 전체 페이지를 읽는 대신, 사용자가 원하는 구간만 읽을 수 있도록 기능을 추가합니다.

</br>

## To-do

- [x] 책 모델에 시작 페이지 및 끝 페이지를 저장하도록 수정하기
- [x] SwiftData 마이그레이션 적용하기
- [x] UI 수정 및 새로운 기능 반영

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
